### ISSUE TITLE
Some problem about importing NDArray 

### ISSUE THREAD

**Issue by Ping-Jung** [visionbike/ME5061-Intelligent-Systems-Theory-and-Practice#1]
Does anyone encounter same problem of unable to import NDArray from Anaconda 3 library packages?
I am able to import this package from PyCharm and VS code except that one.
Problem fixed by open the ipynb files through VS code. (I don't know why)
![擷取](https://user-images.githubusercontent.com/79309902/158396143-9641409c-17a3-4b49-8c3a-e3dba17ef8d4.JPG)

**Comment by visionbike** [comment]
Hi,
Do you activate conda enviroment in pycharm? If you can working well with VS Code, keep working on tis IDE.

TA
