### ISSUE TITLE
Asking about add_antecedent_clause  in fuzzy_rule.py

### ISSUE THREAD

**Issue by Ping-Jung** [visionbike/ME5061-Intelligent-Systems-Theory-and-Practice#3]
Hi  TA:
     May I ask about how to add  multiple rules in the (add antecedent variables) function in fuzzy_rules.py? The function only allows two input variables (like "Temperature", and "Hot"), but we have  to combine two antecedent into one rule (like "Temperature" "Hot" and "Humidity"  "Wet" into one antecedent),  should we separate the antecedent_clauses from add rules(in fuzzy system) first,? but then, how do the system combine it?
Also may I ask about what is "variable is set" in the param var?
![擷取](https://user-images.githubusercontent.com/79309902/159110509-5866eed7-7626-4d70-bb6a-0a5510b83c56.JPG)

**Comment by visionbike** [comment]
Hi,
I have updated new instructions inside the code, please check and update
your local repo.

Kind regards,

Thien-Phuc (Fellix)

Vào Th 7, 19 thg 3, 2022 vào lúc 14:40 Ping-Jung ***@***.***>
đã viết:
